// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzE4tXAY8MaYSWT9vNscHrXfmSe-G9xvY',
    appId: '1:541433307577:web:37d75ac3f0768f6a801668',
    messagingSenderId: '541433307577',
    projectId: 'kabadi-de081',
    authDomain: 'kabadi-de081.firebaseapp.com',
    storageBucket: 'kabadi-de081.appspot.com',
    measurementId: 'G-310LDJ1RRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1aUd2R8VvBf8rygQVBO2ChjUnL3sNkS8',
    appId: '1:541433307577:android:0fa915daec6ac3e2801668',
    messagingSenderId: '541433307577',
    projectId: 'kabadi-de081',
    storageBucket: 'kabadi-de081.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtT_UaLPULDBnj8xTRLA-H_IGPiD3LFbw',
    appId: '1:541433307577:ios:cf155ad178b26272801668',
    messagingSenderId: '541433307577',
    projectId: 'kabadi-de081',
    storageBucket: 'kabadi-de081.appspot.com',
    iosBundleId: 'com.example.proKabadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtT_UaLPULDBnj8xTRLA-H_IGPiD3LFbw',
    appId: '1:541433307577:ios:bb40a6f7d011dad3801668',
    messagingSenderId: '541433307577',
    projectId: 'kabadi-de081',
    storageBucket: 'kabadi-de081.appspot.com',
    iosBundleId: 'com.example.proKabadi.RunnerTests',
  );
}
